codebuds_sylius_fcm_plugin_admin_shop_user_notifications:
    resource: |
        alias: codebuds_sylius_fcm_plugin.shop_user_fcm_notification
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        permission: true
        grid: codebuds_sylius_fcm_plugin_admin_shop_user_notifications
        vars:
            all:
                subheader: codebuds_sylius_fcm_plugin.ui.notification
    type: sylius.resource
