codebuds_sylius_fcm_plugin_admin_shop_user_fcm_notification_create:
    path: /shop-user-fcm-notifications/new
    methods: [ GET, POST, PUT ]
    defaults:
        _controller: codebuds_sylius_fcm_plugin.controller.shop_user_fcm_notification.overridden::createAction
        _sylius:
            template: "@CodeBudsSyliusFCMPlugin/FCMNotifications/ShopUser/create.html.twig"
            section: admin
            permission: true

codebuds_sylius_fcm_plugin_admin_shop_user_notifications:
    resource: |
        alias: codebuds_sylius_fcm_plugin.shop_user_fcm_notification
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        permission: true
        grid: codebuds_sylius_fcm_plugin_admin_shop_user_notifications
        except: ['create']
        vars:
            all:
                subheader: codebuds_sylius_fcm_plugin.ui.notification
    type: sylius.resource
