sylius_grid:
    grids:
        codebuds_sylius_fcm_plugin_admin_shop_user_tokens:
            driver:
                name: doctrine/orm
                options:
                    class: "%codebuds_sylius_fcm_plugin.model.shop_user_fcm_token.class%"
            sorting:
                createdAt: desc
            fields:
                shopUser:
                    type: twig
                    label: codebuds_sylius_fcm_plugin.ui.shop_user
                    options:
                        template: "@CodeBudsSyliusFCMPlugin/Grid/Field/shopUser.html.twig"
                value:
                    type: twig
                    label: sylius.ui.value
                    options:
                        template: "@CodeBudsSyliusFCMPlugin/Grid/Field/token.html.twig"
                createdAt:
                    sortable: true
                    type: datetime
                    label: sylius.ui.created_at
            filters:
                shopUser:
                    type: string
                    label: codebuds_sylius_fcm_plugin.ui.shop_user
                    options:
                        fields: [ shopUser.email, shopUser.customer.firstName, shopUser.customer.lastName ]
                date:
                    type: date
                    label: sylius.ui.date
                    options:
                        field: createdAt
                        inclusive_to: true
