imports:
    - { resource: resources.yml }
    - { resource: grids.yml }
    - { resource: services.yml }
    - { resource: events.yml }
    - { resource: data_transformer.yml }
    - { resource: services/repository.yml }
    - { resource: commands.xml }

parameters:
    codebuds_validation_group: [ codebuds ]
    codebuds_sylius_fcm_plugin.form.type.shop_user_fcm_notification.validation_groups: "%codebuds_validation_group%"
    codebuds_sylius_fcm_plugin.form.type.product_fcm_notification.validation_groups: "%codebuds_validation_group%"

framework:
    serializer:
        mapping:
            paths: [ '%kernel.project_dir%/vendor/codebuds/sylius-fcm-plugin/src/Resources/config/serialization' ]

api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/vendor/codebuds/sylius-fcm-plugin/src/Resources/config/routing/api_resources'

doctrine:
    orm:
        resolve_target_entities:
            CodeBuds\SyliusFCMPlugin\Entity\FCMTokenInterface: CodeBuds\SyliusFCMPlugin\Entity\FCMToken
            CodeBuds\SyliusFCMPlugin\Entity\FCMTopicInterface: CodeBuds\SyliusFCMPlugin\Entity\FCMEntityTopic

sylius_grid:
    grids:
        sylius_admin_product:
            actions:
                item:
                    notify:
                        type: notify
                        label: codebuds_sylius_fcm_plugin.actions.notify
                        options:
                            link:
                                route: codebuds_sylius_fcm_plugin_admin_product_notify
