imports:
    - { resource: services/event_listener.yml }
    - { resource: services/form.yml }
    - { resource: services/controller.yml }
    - { resource: services/service.yml }

services:
    codebuds_sylius_fcm_plugin.grid_field.count:
        class: CodeBuds\SyliusFCMPlugin\Grid\FieldType\CountType
        arguments:
            $dataExtractor: '@sylius.grid.data_extractor'
        tags:
            - { name: sylius.grid_field, type: count }
