sylius_resource:
    resources:
        codebuds_sylius_fcm_plugin.fcm_entity_topic:
            driver: doctrine/orm
            classes:
                model: CodeBuds\SyliusFCMPlugin\Entity\FCMEntityTopic
                interface: CodeBuds\SyliusFCMPlugin\Entity\FCMEntityTopicInterface
