sylius_resource:
    resources:
        codebuds_sylius_fcm_plugin.fcm_token:
            driver: doctrine/orm
            classes:
                model: CodeBuds\SyliusFCMPlugin\Entity\FCMToken
                interface: CodeBuds\SyliusFCMPlugin\Entity\FCMTokenInterface
