sylius_resource:
    resources:
        codebuds_sylius_fcm_plugin.product_fcm_topic:
            driver: doctrine/orm
            classes:
                model: CodeBuds\SyliusFCMPlugin\Entity\ProductFCMTopic
                interface: CodeBuds\SyliusFCMPlugin\Entity\ProductFCMTopicInterface
#                repository: CodeBuds\SyliusFCMPlugin\Repository\ProductFCMTopicRepository
#                controller: CodeBuds\SyliusFCMPlugin\Controller\ProductFCMTopicController
