sylius_resource:
    resources:
        codebuds_sylius_fcm_plugin.shop_user_fcm_notification:
            driver: doctrine/orm
            classes:
                model: CodeBuds\SyliusFCMPlugin\Entity\ShopUserFCMNotification
                interface: CodeBuds\SyliusFCMPlugin\Entity\FCMNotificationInterface
                form: CodeBuds\SyliusFCMPlugin\Form\Type\ShopUserFCMNotificationType
                controller: CodeBuds\SyliusFCMPlugin\Controller\ShopUserFCMNotificationController
