CodeBuds\SyliusFCMPlugin\Entity\ProductFCMTopic:
    type: entity
    table: codebuds_fcm_product_fcm_topic
    manyToOne:
        product:
            targetEntity: Sylius\Component\Product\Model\ProductInterface
            joinTable:
                name: codebuds_fcm_topic_products
                joinColumns:
                    codebuds_fcm_entity_topic_id:
                        referencedColumnName: id
                        onDelete: CASCADE #TODO check this
                inverseJoinColumns:
                    product_id:
                        referencedColumnName: id
                        onDelete: CASCADE #TODO check this
