CodeBuds\SyliusFCMPlugin\Entity\TopicSubscription:
    type: entity
    table: codebuds_fcm_topic_subscription
    id:
        id:
            type: integer
            if: true
            generator:
                strategy: AUTO
    
    manyToOne:
        topic:
            targetEntity: CodeBuds\SyliusFCMPlugin\Entity\FCMEntityTopicInterface
            inversedBy: subscriptions
            cascade:
                - persist
            joinColumns:
                topic_id:
                    referencedColumnName: id
                    onDelete: CASCADE #TODO check this
            inverseJoinColumns:
                topic_subscription_id:
                    referencedColumnName: id
                    onDelete: CASCADE #TODO check this
        
        token:
            fetch: EAGER
            inversedBy: subscriptions
            targetEntity: CodeBuds\SyliusFCMPlugin\Entity\FCMTokenInterface
            joinColumns:
                token_id:
                    referencedColumnName: id
                    onDelete: CASCADE #TODO check this
            inverseJoinColumns:
                topic_subscription_id:
                    referencedColumnName: id
                    onDelete: CASCADE #TODO check this
